### ISSUE TITLE
Mod version selector disabled when earliest version does not support game version

### ISSUE THREAD

**Issue by Miner239** [wispborne/TriOS#12]
![image](https://github.com/wispborne/TriOS/assets/4686046/83324e3d-5be6-43f4-955e-fa3c415e3f65)

Iron Shell 1.18.3ae was for game version .96, while 1.18.3aj is for game version .97. TriOS picked the former for info and blocks the version selector, when I should have been able to switch to the correct version instead.

**Comment by templeofshadow** [comment]
After I closed #26 I saw this issue, and thought to myself "huh, this looks familiar". I quickly installed 1.18.3ae took a look at the version sorting in the drop-down (since I had Iron Shell enabled when I installed Iron Shell 1.18.3ae, it didn't block my selector drop-down), and sure enough: 
![image](https://github.com/wispborne/TriOS/assets/66976515/5905cecb-f322-4e4f-87ad-a71d49b3f1f0)
1.18.3ae is on the top of the list, which implies the same bug causing this as is causing #26. 

I'll leave it to @wispborne to check if this is actually the case, but if it is, it should be fixed (at least on Windows) with commit https://github.com/wispborne/TriOS/commit/32152ee0f39a6642d111d6e5d49eb6074d816cbe.

**Comment by templeofshadow** [comment]
After commenting the above and thinking about it for a while, couldn't the required game version be a good way to sanity check the mod version? Since any letters are removed from the mod version number, in the case of @Miner239's bug, since there are only two versions of the mod that would be treated as identical due to the string sanitization, and they have different required game versions, TriOS could default to whatever ModVariant has the highest required game version as the highest version number, at least when the mod versions have otherwise identical version numbers after sanitization. At the very least, this would prevent the bug of not being able to enable the mods at all. 

Of course, because this specific bug was fixed in the aforementioned commit, this would only occur when the mod doesn't support Version Checker, but it would still be better than nothing in terms of version sorting.

Or am I crazy?

**Comment by wispborne** [comment]
I'll have to think about that idea of using the game version. It's not just highest game version, it'd be matching the current game version (if player is using 0.96), and I need to see if that change can be made in just a couple spots or if it's in a bunch of places...and if it's really needed.

In the meantime, I admit I forgot about this bug, though I did fix it; in 0.0.52, the version selector is not disabled if *any* version supports your current game version.
